# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# LOGGING
logging:
    file: cinema.log

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
# EMBEDDED SERVER CONFIGURATION
server:
    context-path: /cv

# THYMELEAF (ThymeleafAutoConfiguration)
spring:
    thymeleaf:
        cache: false
        prefix: classpath:/vxml/
        suffix: 
        content-type: text/xml
    datasource:
        url: jdbc:mysql://localhost/cinema_reservations?characterEncoding=utf-8
        username: bozena
        password: vxml
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        show-sql: true