# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
# LOGGING
logging:
    file: logs/cinema.log

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
# EMBEDDED SERVER CONFIGURATION
server:
    context-path: /cr

# THYMELEAF (ThymeleafAutoConfiguration)
spring:
    thymeleaf:
        suffix: .xml
        mode: XML
        cache: false
    datasource:
        url: jdbc:mysql://localhost/cinema_reservations?characterEncoding=utf-8
        username: bozena
        password: vxml
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        show-sql: true