# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# LOGGING
logging:
    file: fullLogs.log

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
# EMBEDDED SERVER CONFIGURATION
server:
    context-path: /cv

# THYMELEAF (ThymeleafAutoConfiguration)
spring:
    thymeleaf:
        cache: false
        prefix: classpath:/vxml/
        suffix: 
    datasource:
        url: jdbc:mysql://localhost/cinema_reservations
        username: bozena
        password: vxml
        driverClassName: com.mysql.jdbc.Driver