CREATE TABLE IF NOT EXISTS CUSTOMER (
ID INT AUTO_INCREMENT NOT NULL UNIQUE,
CODE INT(4) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS GENRE (
ID INTEGER AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO GENRE (NAME) VALUES
('horror'),
('komedia'),
('sensacja'),
('akcja'),
('dramat'),
('thriller'),
('familijny'),
('dokumentalny');

CREATE TABLE IF NOT EXISTS MOVIE (
ID INTEGER AUTO_INCREMENT,
TITLE VARCHAR(30) NOT NULL,
GENRE_ID INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID)
);

CREATE TABLE IF NOT EXISTS AUDITORIUM (
ID INTEGER AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SHOWING (
ID INTEGER AUTO_INCREMENT,
MOVIE_ID INTEGER NOT NULL,
AUDITORIUM_ID INTEGER NOT NULL,
BEGIN_TIME TIME NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID),
FOREIGN KEY (AUDITORIUM_ID) REFERENCES AUDITORIUM(ID)
);

CREATE TABLE IF NOT EXISTS SEAT (
ID INTEGER AUTO_INCREMENT,
ROW_NUMBER INTEGER NOT NULL,
AUDITORIUM_ID INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (AUDITORIUM_ID) REFERENCES AUDITORIUM(ID)
);

CREATE TABLE IF NOT EXISTS BOOKING (
ID INTEGER AUTO_INCREMENT,
CUSTOMER_ID INTEGER NOT NULL,
SEAT_ID INTEGER NOT NULL,
AUDITORIUM_ID INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
FOREIGN KEY (AUDITORIUM_ID) REFERENCES AUDITORIUM(ID)
);